ECHO OFF
CLS
ECHO ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
ECHO บ  REoL TOUGH: SATAN'S CASTLE II: HIS NEW HOME IN HELL, AN E3M1 REPLACEMENT  บ
ECHO บ               For DOOM. Other goodies are also included!                   บ
ECHO บ----------------------------------------------------------------------------บ
ECHO บTHE GOODIES:    (1) The original Satan's Castle (1FIFFY2.ZIP) is also inclu-บ
ECHO บ                  ded. This level put REoL TOUGH on the world map! Please   บ
ECHO บ                  note that this file above has no demo. Didn't know how to บ
ECHO บ                  make them then! Has it's own documentation.               บ
ECHO บ                                                                            บ
ECHO บ                (2) New patches to change the chainsaw (deathmatch) and the บ
ECHO บ                  rocket launcher into a drill and flame thrower respective-บ
ECHO บ                  ly. In spite of their text, these files DO back up the    บ
ECHO บ                  parts of the DOOM.WAD it modifies. Run the UNDO.BAT for   บ
ECHO บ                  the one you want to use and your DOOM.WAD is back the way บ
ECHO บ                  it originally was (you may have to rename one of the UNDO บ
ECHO บ                  .BAT file's names, since each one undoes ONE of the weaponบ
ECHO บ                  changes)!   COURTESY OF: Jason Morris                     บ
ECHO ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
PAUSE
CLS
ECHO ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
ECHO บ NEW GRAPHICS: The title screen, PAUSE indicator, and credits screens are   บ
ECHO บ              made by yours truly! I unlocked the power of GRAPHICS!        บ
ECHO บ                                                                            บ
ECHO บ NEW PATCHES: By Jason Morris. Great job! All tested, all worked. These are บ
ECHO บ             the flame thrower and drill you read about.                    บ
ECHO บ                                                                            บ
ECHO บ NEW SOUNDS: By Kevin Hanser. He thought the sounds were so-so, but I did   บ
ECHO บ            think they'd work here, and I think they do!                    บ
ECHO บ                                                                            บ
ECHO บ NEW MUSIC: By Mike Slusher. His synthesiser is down, so I'm rerunning his  บ
ECHO บ           works.:(  Once again, Black Sunshine by White Zombie.            บ
ECHO บ----------------------------------------------------------------------------บ
ECHO บ This PWAD conatains a 9 minute demo. You'll need Ye Olde 1.2 to see it. If บ
ECHO บ you have 1.666 or other, the demo will crash and burn! The level WILL run! บ
ECHO บ      (With all the trouble people have upgrading, it's not worth it!)      บ
ECHO ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
PAUSE
CLS
ECHO ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
ECHO บCOPYRIGHT NOTICE: You MAY modify this level or the graphics, so long as I   บ
ECHO บ                  get the credit for the original work. ALL files (with the บ
ECHO บ                  exceptions of the "goodies") MUST be included!*           บ
ECHO บ                  Copyrights for other materials by others are pending. If  บ
ECHO บ                  You want to use other people's work E-mail them from theirบ
ECHO บ                  addresses below.                                          บ
ECHO บ                                                                            บ
ECHO บ    * FEEL FREE TO DISTRIBUTE THIS LEVEL ANYWHERE! MONEY'S THE LIMIT! :)    บ
ECHO บ--------------------------------------------------------------------------- บ
ECHO บ        THE E-MAIL POST OFFICE DIRECTORY (IF YOU NEED IT FOR HELP)          บ
ECHO บ                                                                            บ
ECHO บ George Fiffy (REoL):             Georgef551@aol.com                        บ
ECHO บ Jason Morris:                    JpMorris15@aol.com                        บ
ECHO บ Mike Slusher:                    Matsuo@aol.com                            บ
ECHO บ Keven Hanser:                    Kmhanser@saturn.acs.oakland.edu           บ
ECHO บ                                                                            บ
ECHO บ PLEASE rmember to send Q's about the patches (flame, drill) to Jason. I am บ
ECHO บ      NOT an expert at enemy/weapon replacement (can't even DO that)!       บ
ECHO ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
PAUSE
CLS
ECHO ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
ECHO บ                            ##### The Story #####                           บ
ECHO บ                                                                            บ
ECHO บ    Not too long ago, you. B.J. Blazcowictz found out where Satan lived whenบ
ECHO บyou were wondering through Hell. As he was preparing his troops for Hell On บ
ECHO บEarth, he left his home, and wreaked havoc on Earth. You then went to his   บ
ECHO บcastle (FIFFY2.WAD) and got even! When he returned home a few months later, บ
ECHO บhe was FURIOUS! Satan got so angry, he built a special school called Satan'sบ
ECHO บSchool of Warfare (WAR4.WAD). On his day off, you went in and slaughtered   บ
ECHO บthe student body, as well as all of his staff. What you didn't know about   บ
ECHO บthis school was that the students were being trained to go to your New York บ
ECHO บpenthouse apartment on your break and destroy you like never before! Good   บ
ECHO บthing you were there early! Just think, if you didn't go there, you would beบ
ECHO บDEAD now! No wife, no children (Hmmm), and worst of all, NO 90210! (Running บ
ECHO บgag. Was in another doc to another level.) You DO want to see the one where บ
ECHO บBrandon's girlfriends take him to Bob Barker to get... Well, you get the    บ
ECHO บpicture! :)                                                                 บ
ECHO บ   You hear the phone ring, and you hesitantly answer it. Colonel Sanders isบ
ECHO บon the line. Oh boy, just what you need on your day off watching the O.J.   บ
ECHO บSIMPSON TRIAL! Sanders told you that Lucifer himself just bought his second บ
ECHO ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
PAUSE
CLS
ECHO ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
ECHO บhome in Hell because you wrecked the first one. You shrug your sholders as  บ
ECHO บthe TV cameramen accidently show the face of a juror. Sanders then told you บ
ECHO บthat Satan is going to pay you a visit. You then wake your family, pack, andบ
ECHO บgo to MOTEL 6 to hide your family, as you go off to meet your fate, while   บ
ECHO บyour family watches TV with 46 channels, all but 5 carrying the O.J. SIMPSONบ
ECHO บTRIAL (That gives you more reasons to play DOOM, doesn't it?). You head to  บ
ECHO บa starirway that goes to Hell and find Satan nowhere, but you do find his   บ
ECHO บnew home in Hell. Since you reflect back and remember that your family is   บ
ECHO บnow safe in a motel, you decide to take the $.50 tour of his home, and do   บ
ECHO บwhat you've done last time, kick butt, and go on a rampage! You'll meet his บ
ECHO บbodyguard at the end, so don't say you were not warned! This is the time to บ
ECHO บget out your weponry and ask: "Who wants to be fried?" You go in, and you   บ
ECHO บfight for your life, and to free the world from havoc (for now).            บ
ECHO ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
PAUSE
CLS
ECHO ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
ECHO บMODES OF PLAY:                                                              บ
ECHO บ Single player and multi: You go through the castle kicking demon butt. In  บ
ECHO บ some places, it seems the demons definately have the upper hand, but know- บ
ECHO บ ing you and your fellow Doomheads, You'll pull through.                    บ
ECHO บ                                                                            บ
ECHO บ Deathmatch: You and up to four Doomheads will start anywhere within the    บ
ECHO บ castle (there are quite a few starting points) and find each other to see  บ
ECHO บ who IS the greatest Doomhead of them all! Also note that it is likely that บ
ECHO บ that you and at LEAST one other Doomhead will start REoL close to one an-  บ
ECHO บ other! Keep an eye out, because you may only live a few seconds, LITTER-   บ
ECHO บ ALLY! This is also the place to test out the DRILL patch!                  บ
ECHO ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
PAUSE
CLS
ECHO ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
ECHO บ                    PLAYING TIPS (in no particualr order):                  บ
ECHO บ                                                                            บ
ECHO บ(1) When you hit the switch that lowers the floor you're standing on, you'llบ
ECHO บ    note that there are three doors with different torches for each. They   บ
ECHO บ    mean something.                                                         บ
ECHO บ                                                                            บ
ECHO บ(2) When you get the ROCKET LAUNCHER (or FLAME THROWER if the patch was usedบ
ECHO บ    to change the launcher), you'll meet "Satan's Bodyguard"! Note that     บ
ECHO บ    there is virtually NO PLACE TO HIDE! Try it on ULTRA-VIOLENCE! (Ha, ha!)บ
ECHO บ                                                                            บ
ECHO บ(3) Be carefull going through the blue key door! That door leads to another บ
ECHO บ    one with DEMONS, IMPS, and LOST SOULS. Once that door behind you closes,บ
ECHO บ    there is NO WAY OUT! The only way out is through! Oh, Don't fall into   บ
ECHO บ    the toxic waste pools. Once you're in, you can't get out! (Heh, Heh!)   บ
ECHO บ                                                                            บ
ECHO บ(4) If DOOM crashes, see what you can collect from insurance. (rimshot)     บ
ECHO ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
PAUSE
CLS
ECHO ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
ECHO บ(5) PLEASE note that there is HOM in this level, done on PURPOSE. These onceบ
ECHO บ    again represent MIRRORS. You don't believe the mail I got about people  บ
ECHO บ    thinking this was a bug in the REoL TOUGH 2 PROJECT! Pays to read this, บ
ECHO บ    doesn't it?                                                             บ
ECHO บ                                                                            บ
ECHO บ(6) SPAM was not meant to be taken internally.                              บ
ECHO บ                                                                            บ
ECHO บ(7) Be careful in the Room O' Crates. You may not know what's hiding there! บ
ECHO บ    (Of course, if you have 1.2, you may know from the demo.)               บ
ECHO บ                                                                            บ
ECHO บ(8) All secrets are invisible on the map. There are no "odd" switches and   บ
ECHO บ    the like. All access is straightfoward. :)                              บ
ECHO บ                                                                            บ
ECHO บ(9) This is what QUAKE will be like (..NOT)!                                บ
ECHO บ                                                                            บ
ECHO บ(10) Use ammo sparingly? WHY? There's PLENTY to go around!                  บ
ECHO บ                                                                            บ
ECHO บ(11) Trust me. I was NOT generous with the medical kits. Looks it though.   บ
ECHO ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
PAUSE
CLS
ECHO ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
ECHO บ(12) I DARE you to go to the center of that big wooden room! You'll get a   บ
ECHO บ     wondeful suprise if you do! I hope you're not desperate for the ammo!  บ
ECHO บ                                                                            บ
ECHO บ(13) The BLUR SPHERE in the Bathroom may be tough to get, but can be taken! บ
ECHO บ--------------------------------------------------------------------------- บ
ECHO บKnown "boo-boo's":                                                          บ
ECHO บ                                                                            บ
ECHO บ(1) That toe you stubbed this morning. That's why God gave us toes, to find บ
ECHO บ    the furniture in the dark.                                              บ
ECHO บ                                                                            บ
ECHO บ(2) That there actually are no problems. Pinch me to see if I'm dreaming!   บ
ECHO ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
PAUSE
CLS
ECHO ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
ECHO บ AOL-ers: Are you STUCK? Do you need help on a REoL TOUGH level? Why not    บ
ECHO บ          visit the REoL TOUGH DOOM LEVEL HELPLINE! Go to PC GAMES and open บ
ECHO บ          up the DOOM subject. Look for the floder marked REoL TOUGH DOOM   บ
ECHO บ          LEVEL HELPLINE.                                                   บ
ECHO บ OTHERS:  Use the E-mail address Georgef551@aol.com                         บ
ECHO บ----------------------------------------------------------------------------บ
ECHO บ I am also on Software Creations: (508)368-7036. If you leave a message for บ
ECHO บ GEORGE FIFFY in confrence 47 (id Software), I'll look for it!              บ
ECHO ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
PAUSE
CLS
ECHO ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
ECHO บ   REoL TOUGH LEVELS:  (NOTE: Some levels may not be found in all areas!)   บ
ECHO บ----------------------------------------------------------------------------บ
ECHO บ 1FIFFY.ZIP, Hell on Earth                Hell is taking over Earth. Stop   บ
ECHO บ             Interpretation               them before the planet is terrib- บ
ECHO บ                                          ly overrun by demons!             บ
ECHO บ                                                                            บ
ECHO บ 1FIFFY2.ZIP, Satan's Castle              While Satan is trashing Earth, whyบ
ECHO บ                                          not get even and trash his home!  บ
ECHO บ                                                                            บ
ECHO บ 1FIFFY3.ZIP, Hotel                       You go to Hell's 5-star hotel, theบ
ECHO บ                                          Under Arms, to rest for the night,บ
ECHO บ                                          or will you rest?                 บ
ECHO บ                                                                            บ
ECHO บ 1FIFFY4.ZIP, The Pit                     The Mt. Everest detention camp is บ
ECHO บ                                          out of control! Shape up those pr-บ
ECHO บ                                          isoners! You'll need to use THE   บ
ECHO บ                                          PIT to get around.                บ
ECHO ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
PAUSE
CLS
ECHO ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
ECHO บ 1FIFFY5.ZIP, St. Lucifer's Church        You come accross an odd church,   บ
ECHO บ                                          when the parishoners start shotingบ
ECHO บ                                          at you! Go investigate the church!บ
ECHO บ                                                                            บ
ECHO บ 1FIFFY6.ZIP, Baron Wasteland             Practically NOTHING but BARONS!   บ
ECHO บ                                          Go through a secret military in-  บ
ECHO บ                                          stalation and kick butt!          บ
ECHO บ                                                                            บ
ECHO บ 1FIFFY7.ZIP, Satan's Castle II: His      A new castle for Satan! Do as you บ
ECHO บ              New Home in Hell            did to his first home!            บ
ECHO บ                                                                            บ
ECHO บ                                                                            บ
ECHO บ 1FIFORIG.ZIP, Total War I (v2.1)         The orriginal REoL TOUGH level!   บ
ECHO บ                                          Fight end-bosses in a huge bowl!  บ
ECHO ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
PAUSE
CLS
ECHO ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
ECHO บ 1FIFWAR1.ZIP, Total War II               A trilogy of WAR! Includes TOTAL  บ
ECHO บ                                          WAR I (v2.0) and two other deadly บ
ECHO บ                                          missions!               !!SLOW!!  บ
ECHO บ                                                                            บ
ECHO บ 1FIFWAR2.ZIP, Total War III: Land        Dark rooms you can see well in,   บ
ECHO บ               of Weirdness               Invisible Buildings, and a ton of บ
ECHO บ                                          other weird worders.    !!SLOW!!  บ
ECHO บ                                                                            บ
ECHO บ 1FIFWAR3.ZIP, Total War IV: Satan's      Go through a school building and  บ
ECHO บ               School of Warfare          get even with the staff and the   บ
ECHO บ                                          Student Body (or BODIES)! !!SLOW!!บ
ECHO บ                                                                            บ
ECHO บ 1FIFWAR4.ZIP, Total War V: Chambers      A secret bomb shelter has been    บ
ECHO บ               of Death                   overrun by demons! Go down there  บ
ECHO บ                                          and get rid of them!    !!SLOW!!  บ
ECHO ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
PAUSE
CLS
ECHO ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
ECHO บ     REoL TOUGH 2 for DOOM II, Hell On Earth: (not available everywhere)    บ
ECHO บ                                                                            บ
ECHO บ 2FIFFY1.ZIP, Guerrila Warfare I:         Go through the unexplored parts ofบ
ECHO บ              Wolfen-Steined!             Castle Wolfenstein and flush out  บ
ECHO บ                                          those demons and nazis!           บ
ECHO บ                                                                            บ
ECHO บ        IN THE WORKS, 2FIFFY2.ZIP, Guerrila Warfare II: Starbase 7          บ
ECHO บ  A trilogy where a friend of yours were kidnapped by demons because he has บ
ECHO บ  unlocked the magical power of Shaving Cream! They took your friend on a   บ
ECHO บ  starship in the middle of nowhere! They didn't know you're also aboard!   บ
ECHO ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
PAUSE
CLS
ECHO ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
ECHO บ I hope you'll enjoy this and any other levels in the future! I'd like to   บ
ECHO บhear from you! Write me. I have no friends! :)                              บ
ECHO บ                                                                            บ
ECHO บ THANKS to all who contributed, and THANKS to you loyal Doomheads for givingบ
ECHO บ this level a try!  THANK YOU!                                              บ
ECHO บ                                                                            บ
ECHO บ Resident Expert of Leominster    Today's Moral: Always toast marshmallows  บ
ECHO บ                                                 when you find a burining   บ
ECHO บ                                                 building.                  บ
ECHO ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
PAUSE
CLS
ECHO Press any key to go to the magical world of DOS.
ECHO.
PAUSE
CLS
