doom2 -playdemo sc01-uv -file scythe.wad
doom2 -playdemo sc02-uv -file scythe.wad
doom2 -playdemo sc03-uv -file scythe.wad
doom2 -playdemo sc04-uv -file scythe.wad
doom2 -playdemo sc05-uv -file scythe.wad
doom2 -playdemo sc06-uv -file scythe.wad
doom2 -playdemo sc07-uv -file scythe.wad
doom2 -playdemo sc08-uv -file scythe.wad
doom2 -playdemo sc09-uv -file scythe.wad
doom2 -playdemo sc10-uv -file scythe.wad
doom2 -playdemo sc11-uv -file scythe.wad
doom2 -playdemo sc12-uv -file scythe.wad
doom2 -playdemo sc13-uv -file scythe.wad
doom2 -playdemo sc14-uv -file scythe.wad
doom2 -playdemo sc15-uv -file scythe.wad
doom2 -playdemo sc16-uv -file scythe.wad
doom2 -playdemo sc17-uv -file scythe.wad
doom2 -playdemo sc18-uv -file scythe.wad
doom2 -playdemo sc19-uv -file scythe.wad
doom2 -playdemo sc20-uv -file scythe.wad
doom2 -playdemo sc21-uv -file scythe.wad
doom2 -playdemo sc22-uv -file scythe.wad
doom2 -playdemo sc23-uv -file scythe.wad
doom2 -playdemo sc24-uv -file scythe.wad
doom2 -playdemo sc25-uv -file scythe.wad
doom2 -playdemo sc26-uv -file scythe.wad
doom2 -playdemo sc27-uv -file scythe.wad
doom2 -playdemo sc28a-uv -file scythe.wad
doom2 -playdemo sc28b-uv -file scythe.wad
doom2 -playdemo sc28-uv -file scythe.wad
doom2 -playdemo sc29-uv -file scythe.wad
doom2 -playdemo sc30-uv -file scythe.wad
doom2 -playdemo sc31-uv -file scythe.wad
doom2 -playdemo sc32-uv -file scythe.wad
doom2 -playdemo sc01-nm -file scythe.wad
doom2 -playdemo sc02-nm -file scythe.wad
doom2 -playdemo sc03-nm -file scythe.wad
doom2 -playdemo sc04-nm -file scythe.wad
doom2 -playdemo sc06-nm -file scythe.wad
doom2 -playdemo sc07-nm -file scythe.wad
doom2 -playdemo sc08-nm -file scythe.wad
doom2 -playdemo sc09-nm -file scythe.wad
doom2 -playdemo sc10-nm -file scythe.wad
doom2 -playdemo sc11-nm -file scythe.wad
doom2 -playdemo sc12-nm -file scythe.wad
doom2 -playdemo sc13-nm -file scythe.wad
doom2 -playdemo sc17-nm -file scythe.wad
doom2 -playdemo sc18-nm -file scythe.wad
doom2 -playdemo sc19-nm -file scythe.wad
doom2 -playdemo sc20-nm -file scythe.wad
doom2 -playdemo sc21-nm -file scythe.wad
doom2 -playdemo sc23-nm -file scythe.wad
doom2 -playdemo sc24-nm -file scythe.wad
doom2 -playdemo sc25-nm -file scythe.wad
doom2 -playdemo sc26-nm -file scythe.wad
doom2 -playdemo sc27-nm -file scythe.wad
doom2 -playdemo sc28-nm -file scythe.wad
doom2 -playdemo sc30-nm -file scythe.wad
doom2 -playdemo sc31s-nm -file scythe.wad
doom2 -playdemo sc01-sp -file scythe.wad
doom2 -playdemo sc02-sp -file scythe.wad
doom2 -playdemo sc03-sp -file scythe.wad
doom2 -playdemo sc04-sp -file scythe.wad
doom2 -playdemo sc05-sp -file scythe.wad
doom2 -playdemo sc06-sp -file scythe.wad
doom2 -playdemo sc07-sp -file scythe.wad
doom2 -playdemo sc08-sp -file scythe.wad
doom2 -playdemo sc09-sp -file scythe.wad
doom2 -playdemo sc10-sp -file scythe.wad
doom2 -playdemo sc11-sp -file scythe.wad
doom2 -playdemo sc12-sp -file scythe.wad
doom2 -playdemo sc13-sp -file scythe.wad
doom2 -playdemo sc14-sp -file scythe.wad
doom2 -playdemo sc15-sp -file scythe.wad
doom2 -playdemo sc15s-sp -file scythe.wad
doom2 -playdemo sc16-sp -file scythe.wad
doom2 -playdemo sc17-sp -file scythe.wad
doom2 -playdemo sc18-sp -file scythe.wad
doom2 -playdemo sc19-sp -file scythe.wad
doom2 -playdemo sc20-sp -file scythe.wad
doom2 -playdemo sc21-sp -file scythe.wad
doom2 -playdemo sc22-sp -file scythe.wad
doom2 -playdemo sc23-sp -file scythe.wad
doom2 -playdemo sc24-sp -file scythe.wad
doom2 -playdemo sc25-sp -file scythe.wad
doom2 -playdemo sc26-sp -file scythe.wad
doom2 -playdemo sc27-sp -file scythe.wad
doom2 -playdemo sc28-sp -file scythe.wad
doom2 -playdemo sc29-sp -file scythe.wad
doom2 -playdemo sc30-sp -file scythe.wad
doom2 -playdemo sc31-sp -file scythe.wad
doom2 -playdemo sc31s-sp -file scythe.wad
doom2 -playdemo sc32-sp -file scythe.wad
